export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESSFUL';
export const AUTH_SIGNIN_ERROR = 'AUTH_SIGNIN_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SSUCCESS = 'GET_POSTS_SSUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const SET_UNSUBSCRIBE_LISTEN_POSTS = 'SET_UNSUBSCRIBE_LISTEN_POSTS';
export const STOP_LISTEN_POSTS = 'STOP_LISTEN_POSTS';

export const REMOVE_POST = 'REMOVE_POSTS';
export const REMOVE_POST_SSUCCESS = 'REMOVE_POSTS_SSUCCESS';
export const REMOVE_POST_ERROR = 'REMOVE_POSTS_ERROR';

export const NEW_POST = 'NEW_POST';
export const NEW_POST_SUCESS = 'NEW_POST_SUCESS';
export const NEW_POST_ERROR = 'NEW_POST_ERROR';

export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_SUCESS = 'EDIT_POST_SUCESS';
export const EDIT_POST_ERROR = 'EDIT_POST_ERROR';

export const RESET = 'RESET';
